channels:
  - conda-forge
dependencies:
  - python=3
  - matplotlib
  - numpy
  - bokeh
  - dask
  - distributed
  - jupyterlab
  - netcdf4
  - pandas
  - xarray
  - cartopy
  - zarr 
  - gcsfs 
  - cftime 
  - nc-time-axis
  - eofs
