channels:
  - conda-forge
dependencies:
  - cartopy
  - jupyter
  - xarray
  - matplotlib
  - cftime
  - nc-time-axis
  - pandas
  - python
  - numpy
  - eofs
  - zarr
  - gcsfs
  - bokeh
  - tornado
  - distributed
